### ISSUE TITLE
No configuration setting found for key 'spray'

### ISSUE THREAD

**Issue by boeboe** [Landoop/kafka-addons#1]
Hi,

I have troubles running the slack connector. When starting it in single mode, I get the following error during initialization.

	[ERROR] [10/21/2016 11:28:29.465] [ScalaKafkaBot-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(ScalaKafkaBot)] Uncaught error from thread [ScalaKafkaBot-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
	java.lang.ExceptionInInitializerError
		at io.scalac.slack.api.ApiActor$$anonfun$receive$1.applyOrElse(ApiActor.scala:24)
		at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
		at io.scalac.slack.api.ApiActor.aroundReceive(ApiActor.scala:12)
		at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
		at akka.actor.ActorCell.invoke(ActorCell.scala:495)
		at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
		at akka.dispatch.Mailbox.run(Mailbox.scala:224)
		at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
		at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
		at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
		at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spray'
		at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
		at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
		at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
		at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
		at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
		at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)
		at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)
		at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
		at spray.can.HttpExt.<init>(Http.scala:143)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(ReflectiveDynamicAccess.scala:32)
		at scala.util.Try$.apply(Try.scala:192)
		at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
		at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
		at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:755)
		at akka.actor.ExtensionId$class.apply(Extension.scala:79)
		at akka.actor.ExtensionKey.apply(Extension.scala:149)
		at akka.io.IO$.apply(IO.scala:26)
		at spray.client.pipelining$.sendReceive(pipelining.scala:35)
		at io.scalac.slack.api.SlackApiClient$.<init>(SlackApiClient.scala:24)
		at io.scalac.slack.api.SlackApiClient$.<clinit>(SlackApiClient.scala)
		... 12 more

	Uncaught error from thread [ScalaKafkaBot-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ScalaKafkaBot]
	java.lang.ExceptionInInitializerError
		at io.scalac.slack.api.ApiActor$$anonfun$receive$1.applyOrElse(ApiActor.scala:24)
		at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
		at io.scalac.slack.api.ApiActor.aroundReceive(ApiActor.scala:12)
		at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
		at akka.actor.ActorCell.invoke(ActorCell.scala:495)
		at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
		at akka.dispatch.Mailbox.run(Mailbox.scala:224)
		at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
		at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
		at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
		at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spray'
		at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
		at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
		at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
		at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
		at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
		at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)
		at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)
		at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
		at spray.can.HttpExt.<init>(Http.scala:143)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(ReflectiveDynamicAccess.scala:32)
		at scala.util.Try$.apply(Try.scala:192)
		at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
		at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
		at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:755)
		at akka.actor.ExtensionId$class.apply(Extension.scala:79)
		at akka.actor.ExtensionKey.apply(Extension.scala:149)
		at akka.io.IO$.apply(IO.scala:26)
		at spray.client.pipelining$.sendReceive(pipelining.scala:35)
		at io.scalac.slack.api.SlackApiClient$.<init>(SlackApiClient.scala:24)
		at io.scalac.slack.api.SlackApiClient$.<clinit>(SlackApiClient.scala)
		... 12 more

I am using sbt assembly plugin to create a fatJar:

	assemblyMergeStrategy in assembly := {
	  case PathList("META-INF", xs@_*) => MergeStrategy.discard
	  case x => MergeStrategy.first
	}

	assemblyJarName in assembly := name.value + "-" + version.value + ".jar"

Best regards,
Bart

**Comment by boeboe** [comment]
FYI,

I was able to fix the issues by changing assemblyMergeStrategy I was using to create fatjar with SBT:

	assemblyMergeStrategy in assembly := {
	  case n if n.startsWith("reference.conf") => MergeStrategy.concat
	  case PathList("META-INF", xs@_*) => MergeStrategy.discard
	  case x => MergeStrategy.first
	}

Works like a charm now!

**Comment by samudurand** [comment]
@boeboe you saved my day !
